#!/bin/bash

file=$1
sum=0

make libobjdata.so
if [ -f stats.txt ];then
echo "File exist removing existing stats file"
rm stats.txt
else
echo "Stats file not yet exist. Creating file"
touch stats.txt
fi
if [ -f getsections_dl ];then
echo "Binary file exist"
else
echo "Making Binary File"
make getsections_dl
fi
if [ -f getsyms_dl ];then
echo "Binary file exist"
else
echo "Making Binary File"
make getsyms_dl
fi

for ((i=1; i <51 ;i++));
do
    output=$(./getsections_dl getsections_dl | tail -1)

    (( sum += $output ))
    echo "GetSectionsDL $i times: $output" >> stats.txt
    
done
avg=$(($sum/50))
echo Average for getsections_dl: $avg ms"(milliseconds)">> stats.txt 
echo "" >> stats.txt

sumo=0
for ((i=1; i <51 ;i++));
do
    output1=$(./getsyms_dl getsyms_dl RTLD_LAZY| head -1) 
    echo "GetSymsDL $i times: $output1" >> stats.txt
    #echo $i $output >> stats.txt
    (( sumo += $output1 ))
done
avg2=$(($sumo / 50))
echo Average for getsyms_dl with RTLD_LAZY: $avg2 ms"(milliseconds)">> stats.txt 
echo "">>stats.txt
sumo=0
for ((i=1; i <51 ;i++));
do
    output1=$(./getsyms_dl getsyms_dl RTLD_NOW| head -1) 
    echo "GetSymsDL $i times: $output1" >> stats.txt
    #echo $i $output >> stats.txt
    (( sumo += $output1 ))
done
avg2=$(($sumo / 50))
echo Average for getsyms_dl with RTLD_NOW: $avg2 ms"(milliseconds)">> stats.txt 
