#!/bin/bash
# make libobjdata.so
make test
echo "Testing objcopy in gettext ..."
make gettext 
./gettext test
echo "" 
objcopy -O binary --only-section=.text test text-output1

echo "Checking for same output for objcopy ..."
diff -q text-output1 text-output
echo "Same text output!"
echo "PASS 1/1"
echo ""

